// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGrvHFY0t2NsorNxH0aVIlKymSebVgG6E',
    appId: '1:656553835829:web:62860a3516359a92a2207c',
    messagingSenderId: '656553835829',
    projectId: 'first-firebase-app-class',
    authDomain: 'first-firebase-app-class.firebaseapp.com',
    databaseURL: 'https://first-firebase-app-class-default-rtdb.firebaseio.com',
    storageBucket: 'first-firebase-app-class.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3I7xrzPwafeJmPGOzp6hOKxckvF0qVek',
    appId: '1:656553835829:android:3b925c33e59e2ad7a2207c',
    messagingSenderId: '656553835829',
    projectId: 'first-firebase-app-class',
    databaseURL: 'https://first-firebase-app-class-default-rtdb.firebaseio.com',
    storageBucket: 'first-firebase-app-class.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCii3VSzO9hNag6qWsos1EaB07QoLeInA8',
    appId: '1:656553835829:ios:a45c2dbb3c43f8eaa2207c',
    messagingSenderId: '656553835829',
    projectId: 'first-firebase-app-class',
    databaseURL: 'https://first-firebase-app-class-default-rtdb.firebaseio.com',
    storageBucket: 'first-firebase-app-class.appspot.com',
    iosBundleId: 'com.example.practiceAppClass',
  );
}
